#!/bin/bash

################################################################################
# Author: Sebastien CORBEAU <corbeau.sebastien@yahoo.fr>
# Date: 2023-12-20
# Brief: This script generate C header file contains the tag and SHA1 commit of
#        GIT repository.
################################################################################

if [ $# -lt 1 ]; then
    echo "Generate C header contains GIT tag version and SHA1 commit " \
         "in <output>"
    echo "Optionnaly user could force TAG and SHA1 version."
    echo "Usage $0 <output> [TAG] [SHA1]"
    exit 1
fi

if [ ! -d "${PWD}/.git" ]; then
    echo "Not a git repository"
else
    rm -rf $1

    if [ $# -eq 2 ]; then
        if [ "$2" != "" ]; then
            TAG=$2
        else
            TAG="INVALID_TAG"
        fi
        SHA1="SHA1_NOT_FORCE"
    elif [ $# -ge 3 ]; then
        if [ "$2" !=  "" ]; then
            TAG=$2
        else
            TAG="INVALID_TAG"
        fi

        if [ "$3" !=  "" ]; then
            GIT_SHA1=$3
        else
            GIT_SHA1="INVALID_SHA1"
        fi
    else
        TAG=$(git describe --tag --dirty=-DIRTY)
        if [ $? -ne 0 ]; then
            TAG="NO_TAG"
        fi

            SHA1=$(git rev-parse HEAD)
        if [ $? -ne 0 ]; then
            SHA1="NO_SHA1"
        fi
    fi

    SOFT_NAME=$(basename $(git rev-parse --show-toplevel))
    if [ $? -ne 0 ]; then
        SOFT_NAME="NO_SOFTWARE_NAME"
    fi

    USER_NAME=$(git config user.name)
    USER_MAIL=$(git config user.email)

    if [ -z "$USER_NAME" ]; then
        USER_NAME="Unknown User"
    fi

    if [ -z "$USER_MAIL" ]; then
        USER_MAIL="Unknown mail"
    fi

    echo "/*!" > $1
    echo " * @file: $(basename $1)" >> $1
    echo " * @date: $(date '+%Y-%m-%d')" >> $1
    echo " * @author: This file is auto generated by $(basename $0) executed by"\
        "$USER_NAME <$USER_MAIL>" >> $1
    echo " * @brief: Declaration of software revision get from GIT repository." >> $1
    echo " */" >> $1
    echo "#ifndef GIT_REVISION_H__" >> $1
    echo "#define GIT_REVISION_H__" >> $1
    echo "" >> $1
    echo "#define GIT_TAG   \"$TAG\"" >> $1
    echo "#define GIT_SHA1  \"$SHA1\"" >> $1
    echo "#define SOFT_NAME \"$SOFT_NAME\"" >> $1
    echo "" >> $1
    echo "#endif /* GIT_REVISION_H__ */" >> $1
fi
